.TH CVIEW 1 "April 2012" "PNL" "CVIEW"
.SH NAME
cview \- cluster viewing application
.SH SYNOPSIS
.B cview
.I "[-c foo]"
.br
.SH DESCRIPTION
When invoked with the
.I "-c"
.B cview
reads the cview file and loads the associated data sets from the file.
.SH EXAMPLES
.LP run cview
.IP
cview -c auto.cview
.SH "SEE ALSO"
cviewall(1), oscview(1)
