.TH OSCVIEW 1 "April 2012" "PNL" "OSCVIEW"
.SH NAME
oscview \- cluster viewing application
.SH SYNOPSIS
.B oscview
.I "[-c foo]"
.br
.SH DESCRIPTION
When invoked with the
.I "-c"
.B oscview
reads the cview file and loads the associated data sets from the file.
.SH EXAMPLES
.LP run oscview
.IP
oscview -c auto.cview
.SH "SEE ALSO"
cviewall(1), cview(1)
