#!/usr/bin/env python
"""

This file is port of the CVIEW graphics system, which is goverened by the following License

Copyright © 2008,2009, Battelle Memorial Institute
All rights reserved.

1.	Battelle Memorial Institute (hereinafter Battelle) hereby grants permission
	to any person or entity lawfully obtaining a copy of this software and
	associated documentation files (hereinafter “the Software”) to redistribute
	and use the Software in source and binary forms, with or without
	modification.  Such person or entity may use, copy, modify, merge, publish,
	distribute, sublicense, and/or sell copies of the Software, and may permit
	others to do so, subject to the following conditions:

	•	Redistributions of source code must retain the above copyright
		notice, this list of conditions and the following disclaimers. 
	•	Redistributions in binary form must reproduce the above copyright
		notice, this list of conditions and the following disclaimer in the
		documentation and/or other materials provided with the distribution.
	•	Other than as used herein, neither the name Battelle Memorial
		Institute or Battelle may be used in any form whatsoever without the
		express written consent of Battelle.  
	•	Redistributions of the software in any form, and publications based
		on work performed using the software should include the following
		citation as a reference:

			(A portion of) The research was performed using EMSL, a
			national scientific user facility sponsored by the
			Department of Energy's Office of Biological and
			Environmental Research and located at Pacific Northwest
			National Laboratory.

2.	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
	ARE DISCLAIMED. IN NO EVENT SHALL BATTELLE OR CONTRIBUTORS BE LIABLE FOR ANY
	DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
	ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
	THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

3.	The Software was produced by Battelle under Contract No. DE-AC05-76RL01830
	with the Department of Energy.  The U.S. Government is granted for itself
	and others acting on its behalf a nonexclusive, paid-up, irrevocable
	worldwide license in this data to reproduce, prepare derivative works,
	distribute copies to the public, perform publicly and display publicly, and
	to permit others to do so.  The specific term of the license can be
	identified by inquiry made to Battelle or DOE.  Neither the United States
	nor the United States Department of Energy, nor any of their employees,
	makes any warranty, express or implied, or assumes any legal liability or
	responsibility for the accuracy, completeness or usefulness of any data,
	apparatus, product or process disclosed, or represents that its use would
	not infringe privately owned rights.  

"""

import os    
import sys
import time
import struct
import math
from Numeric import Float32,array,zeros


#Settings 
xmin=-20.0
xmax=20.0
xpoints=500

ymin=-20.0
ymax=20.0
ypoints=500

#(xmin,xmax,ymin,ymax)=(-2.0,0.5,-1.0,1.0)

#Function
def datafunc1(x,y):
	"Binary Op Fun"
	#return abs(math.sin(x)*math.tan(y)/(time.time()%30+1))
	#x+=time.time()%xpoints
	#x %= xpoints
	#if x>xmax:
	#	x -= (xmax-xmin)
	
	#return	int(time.time())%30+1
	return abs(int(x*10)&int(y*10))

def mandel(x,y):
	"Mandelbrot"
	limit=4
	scale=0.0004
	a1=x*scale
	b1=y*scale
	lp=0;
	while lp<=255 and (a1**2+b1**2) <= limit:
		lp+=1
		a2=a1**2-b1**2+x
		b2=2.0*a1*b1+y
		a1=a2
		b1=b2

	return lp

def sombrero(x,y):
	"Sombrero Function"
	s=math.sqrt(x**2+y**2)
	if s==0.0:
		return 0.3
	else:
		return 0.3+math.sin(s)/s


class filer(file):
	def __init__(self,name,mode='r',buffering=32768):
		self._realname = name
		self._tmpname = os.tempnam(".",name);
		file.__init__(self,self._tmpname,mode,buffering)
        
	def close(self):
		ret = file.close(self)
		os.rename(self._tmpname,self._realname)
		return ret


def main(func):
	data=zeros((xpoints,ypoints),Float32)
	xd = (xmax-xmin)/xpoints
	yd = (ymax-ymin)/ypoints
	for i in range(xpoints):
		for j in range(ypoints):
			data[i,j]=func(xmin+xd*i,ymin+yd*j)

	out=filer("xtick","w")
	for i in range(xpoints):
		out.write(struct.pack("32s",str(xmin+xd*i)))
	out.close()

	out=filer("info.ytick","w")
	for j in range(ypoints):
		out.write(struct.pack("32s",str(ymin+yd*j)))
	out.close()

	out=filer("info.desc","w")
	out.write(func.__doc__)
	out.close()

	out=filer("info.rate","w")
	out.write("")
	out.close()

	out=filer("info.data","w")
	out.write(data.tostring())
	out.close()

	out=filer("index","w")
	out.write("info\n")
	out.close()


if __name__ == "__main__":
	main(datafunc1)
